### ISSUE TITLE
Bug(s) in src/vfvm_assemblydata.jl

### ISSUE THREAD

**Issue by jotaraz** [j-fu/VoronoiFVM.jl#103]
In two functions in src/vfvm_assemblydata.jl the `iparam`-for-loop to be moved into some other loops such that all used variables are defined.

- [line 337](https://github.com/j-fu/VoronoiFVM.jl/blob/b176ec7ac92df3094f3864ea1fd47d78b6c8d08a/src/vfvm_assemblydata.jl#L337): `@inline function assemble_res_jac(edge...` the `iparam`-for-loop has to be inside the `isnodespecies(system, ispec, K)` if-statement, otherwise `idofL` is not defined.

- [line 400](https://github.com/j-fu/VoronoiFVM.jl/blob/b176ec7ac92df3094f3864ea1fd47d78b6c8d08a/src/vfvm_assemblydata.jl#L400): `@inline function assemble_res_jac(bedge...` the `iparam`-for-loop has to be inside `idofK` for-loop and the `isnodespecies(system, ispec, K)` if-statement, otherwise `idofK` and `idofL` are not defined.

In the first function:
![bug_in_assemblydata](https://github.com/j-fu/VoronoiFVM.jl/assets/33379677/5bd0dff1-3d72-4b19-9c49-dc173b379392)

**Comment by j-fu** [comment]
Well, Julia's scoping rules are different from C/C++...

This code is tested in Example430. It worked for two reasonds:

- once idofL is set to some value, it is defined also outside the  if/end clause, as this does not create a [scope block](https://docs.julialang.org/en/v1/manual/variables-and-scoping/#man-scope-table)

- The example is 1D, so there is only one possible value of idofL

... need to add a multispecies test here, so I keep this open...
