### ISSUE TITLE
Use of nodeflux for given flux and not only predefined one

### ISSUE THREAD

**Issue by dilaraabdel** [j-fu/VoronoiFVM.jl#150]
Hey @j-fu!
As we discussed in person, it would be nice to have a [nodeflux method](https://github.com/WIAS-PDELib/VoronoiFVM.jl/blob/49e009f19f2f687a8c541b68f5001a0c96a13dc4/src/vfvm_postprocess.jl#L150), where we can pass an input function, similarly as for the [integrate method](https://github.com/WIAS-PDELib/VoronoiFVM.jl/blob/49e009f19f2f687a8c541b68f5001a0c96a13dc4/src/vfvm_postprocess.jl#L17). Currently, nodeflux depends on the system via using[ ResEvaluator()](https://github.com/WIAS-PDELib/VoronoiFVM.jl/blob/49e009f19f2f687a8c541b68f5001a0c96a13dc4/src/vfvm_postprocess.jl#L168).

The motivation for this is: 
Suppose you have a drift-diffusion current density $j =  j_{\mathrm{drift}} +  j_{\mathrm{diff}}$, where $j$ is discretized via the flux method.
Currently, we can only reconstruct the whole flux via nodeflux but not the two components.

As way around, one can set up a whole new system with a new flux. 
However, this is inconvenient, since it is not possible to copy a System nor overwrite the flux ...

I have written an example for this which I cannot attach unfortunately, but can e-mail you!

**Comment by j-fu** [comment]
Will be available in v2.6 in a couple of minutes.

**Comment by dilaraabdel** [comment]
thanks @j-fu. I just checked it and compared it with the work around. Works perfectly fine!
