### ISSUE TITLE
Discontinous quantities: unexpected behavior

### ISSUE THREAD

**Issue by fafroo** [j-fu/VoronoiFVM.jl#31]
Setting `react =0.0` in 
https://github.com/j-fu/VoronoiFVM.jl/blob/8a7776fe09f331ca1aec238fc5e1fc347265a979/examples/Example420_DiscontinuousQuantities.jl#L104

turns the `dspec` the `DiscontinuousQuantity` in continuous one:

![discontinous_a](https://user-images.githubusercontent.com/14977619/153239696-b10b41a3-d840-4bd7-a5ae-6e91c80a1694.png)

I'd expect to see some sort of a step function -- depending on the initial condition. 
@j-fu @dilaraabdel  is this behavior as intended?

**Comment by dilaraabdel** [comment]
Its strange ... Because this would be my output, if setting react to zero:

![Figure_1](https://user-images.githubusercontent.com/55620957/153241910-f572d4ac-ec8e-4628-ae23-42ddc534fc5d.png)

Can you show all adjustments?

**Comment by j-fu** [comment]
I second @dilaraabdel  -  I see the same result. Also be careful, due to the effectively missing (resp. homogeneous Neumann) boundary conditions, the solution for dspec in the interior domains is unique up to a constant.

**Comment by fafroo** [comment]
@j-fu & @dilaraabdel you're right, the problem is on my side. I've tried a fresh copy and it returns a piece-wise constant solution.

The continuous behavior was due to tinkering with the `regionspec` field. I set it all constant, which perhaps made the quantity continuous again :).
