### ISSUE TITLE
Could please help to solve this problem?

### ISSUE THREAD

**Issue by MrBenzWorld** [j-fu/VoronoiFVM.jl#54]
Could you please help to solve it in Julia with VoronoiFVM?
I can do it in ansys fluent , but I want learn Julia. 

oscillating flow through pipe (2D)
it is a transient compressible, viscous 2D flow problem. also, conventional heat transfer considers from the pipe wall.
it is a convention diffusion problem. at both ends, there are porous heat exchangers.

Thank you

**Comment by j-fu** [comment]
Hi, thanks for asking.

Your problem does not fall into the problem class supported by this package. You may investigate some other packages for this purpose: Trixi.jl, GridAP.jl or GradientRobustMultiPhysics.jl .

**Comment by MrBenzWorld** [comment]
Thank you for your response @j-fu
